[metadata]
name = django-eval
version = 0.1.0
description = A Django reusable app providing a secure, configurable rule engine powered by SimpleEval
long_description = file: README.rst
long_description_content_type = text/x-rst
author = Dakken
license = MIT

[options]
packages = find:
include_package_data = True
python_requires = >=3.10
install_requires =
    Django>=3.2,<=6.0
    djangorestframework>=3.11
    simpleeval>=0.9.13

[options.extras_require]
redis =
    redis>=3.5
    django-redis>=5.4
test =
    pytest>=6.0
    pytest-django>=4.0

[options.packages.find]
exclude = tests tests.* examples examples.*

[flake8]
max-line-length = 120
exclude = migrations,docs,.git,__pycache__,examples

[check-manifest]
ignore =
    *.pyc
    .travis.yml
    .coveragerc